### ISSUE TITLE
Segmenting ground using isaac_ros_bi3d

### ISSUE THREAD

**Issue by vishrutskaushik** [NVIDIA-ISAAC-ROS/isaac_ros_depth_segmentation#14]
Hello,
I am trying to segment out ground using Nvidia ISAAC ROS. I already have Isaac ROS DNN Stereo Disparity running but I want to mask out the ground from its output either in Disparity image or pointcloud.
Any inputs would be really appreciated on how I can use Bi3D for the same since it already segments out ground. Additionally, how to customize the zones Bi3D detects?
Thanks in advance!

**Comment by hemalshahNV** [comment]
Bi3D detects the ground plan (anything on the floor not taller than ~2cm) to segment it for meaningful output. You can configure the zones (disparity planes) using the Bi3DNode parameters (see [here](https://isaac_ros.gitlab-master-pages.nvidia.com/isaac_ros_docs/repositories_and_packages/isaac_ros_depth_segmentation/isaac_ros_bi3d/index.html#ros-parameters) for the "disparity_values" parameter). Also, take a look at [Isaac ROS Freespace Segmentation](https://isaac_ros.gitlab-master-pages.nvidia.com/isaac_ros_docs/repositories_and_packages/isaac_ros_freespace_segmentation/index.html) which specifically uses the Bi3D model to extract out the segmented floor for you.
